# Autogenerated wrapper script for Gnuplot_jll for x86_64-w64-mingw32-cxx11
export gnuplot

using LibGD_jll
using Qt5Svg_jll
using Cairo_jll
using Libiconv_jll
JLLWrappers.@generate_wrapper_header("Gnuplot")
JLLWrappers.@declare_executable_product(gnuplot)
function __init__()
    JLLWrappers.@generate_init_header(LibGD_jll, Qt5Svg_jll, Cairo_jll, Libiconv_jll)
    JLLWrappers.@init_executable_product(
        gnuplot,
        "bin\\gnuplot.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
